version: "3"
services:
  mysql-docker:
    image: arm64v8/mariadb
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: qwerqwer123
      MYSQL_DATABASE: rediswithspring
      MYSQL_USER: paul
      MYSQL_PASSWORD: qwerqwer123
    container_name: "docker-maria"
    volumes:
      - ./example-docker-data/maria:/var/lib/mysql

  redis-docker:
    image: redis:latest
    command: redis-server --port 6379
    container_name: "docker-redis"
    volumes:
      - ./example-docker-data/redis:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

  spring-app:
    build:
      context: .  # Spring 애플리케이션의 Dockerfile이 있는 디렉토리 경로
    ports:
      - "8080:8080"  # Spring 애플리케이션의 포트
    depends_on:
      - mysql-docker  # Spring 애플리케이션이 MySQL에 의존함
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker:3306/rediswithspring
      SPRING_DATASOURCE_USERNAME: paul
      SPRING_DATASOURCE_PASSWORD: qwerqwer123
    container_name: "docker-spring"
    volumes:
      - ./build/libs:/app/build/libs